name: workflows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: |
          rustup toolchain install nightly --allow-downgrade -c rustfmt
          cargo +nightly fmt -- --check
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          rustup override set 1.85.0
          cargo update
          cargo check --all-features --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clippy
        run: |
          cargo clippy --verbose -- -Dwarnings
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          cargo test --verbose
  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          rustup component add --toolchain=nightly miri
          export MIRIFLAGS="-Zmiri-permissive-provenance"
          cargo +nightly miri test --verbose
